### ISSUE TITLE
z-base 32: potential bug: decoding inaccuracy

### ISSUE THREAD

**Issue by hlubovac** [wiry-net/Base32#2]
I'm not sure if I expect the library to do something that the algorithm doesn't support, but `Wiry.Base32.Base32Encoding.ZBase32.ToBytes`, given different values, produces exact same set of bytes. For example, this particular string, and any other that is comprised by the same and another character appended, produces the same set of bytes below.

base:
"gr3doqbw8radnqb3go"

other that produce same binary:
"gr3doqbw8radnqb3goa"
"gr3doqbw8radnqb3gob"
"gr3doqbw8radnqb3goc"
"gr3doqbw8radnqb3god"

{byte[11]}
    [0]: 49
    [1]: 50
    [2]: 56
    [3]: 56
    [4]: 52
    [5]: 57
    [6]: 48
    [7]: 49
    [8]: 56
    [9]: 57
    [10]: 52

I guess, if the length of the `encoded` argument doesn't match the algorithm, I would expect an error, rather than trailing characters being ignored. This is very important to me, as I'm using these values as data identifiers, and while "gr3doqbw8radnqb3go" points to existing data record, I don't want to make it appear that ""gr3doqbw8radnqb3goa" is an alias to it. Please provide some guidance. If there is any work-around (e.g. my validating the length of the string using some formula, prior to feeding it to the 'ToBytes' method), please tell me.

Thanks!

**Comment by hlubovac** [comment]
For the time being, I'm decoding the entrusted zbase32 input, then encoding the decoding-result back to zbase32, then comparing the encoding-result with the untrusted input. For example:

string untrusted-zbase32:
"gr3doqbw8radnqb3goa"
`Base32Encoding.ZBase32.ToBytes` + `Encoding.UTF8.GetString`  produce decoding-result:
"12884901894" (which is same the result when "gr3doqbw8radnqb3go" + any-[valid]-char is decoded)

Then, to validate, I zbase32 encode the "decoding-result":
`Base32Encoding.ZBase32.GetString("12884901894")`, which gives me this:
"gr3doqbw8radnqb3go"

Since "gr3doqbw8radnqb3go" != "gr3doqbw8radnqb3goa" (trailing "a" char), I conclude that the input is bad.

Any other more performant suggestion would be appreciated.
Thanks.

**Comment by dmitry-ra** [comment]
zbase32 encoding have some unobvious "alias" combinations. For example "r3oo" and "r3oi" decoded as "&a" string. If we convert "&a" string to zbase32 we get "r3oo" string, so "r3oo" is a primary value rather than "r3oi" (an alias).

Best workaround is: generate an identifiers as a bytes and then convert it to zbase32 by Base32Encoding.ZBase32.GetString method.

But I agree, that current input validation is poor and this is cause a [bug](https://github.com/wiry-net/Base32/issues/3) you have found.

**Comment by dmitry-ra** [comment]
I plan to add a method to verify input zbase32 string. So ToBytes method will just work with "primary" and with "alias" values, but users can be able to check their data if they need.

**Comment by dmitry-ra** [comment]
@hlubovac FYI: validation feature shipped in [v1.1.1](https://github.com/wiry-net/Wiry.Base32/releases/tag/v1.1.1)
