### ISSUE TITLE
zbase32: decoding certain input fails

### ISSUE THREAD

**Issue by hlubovac** [wiry-net/Base32#3]
Example text: "gaaaaaaaa"

The exception is weird; I can't even "catch" it. While debugging, VS serves me the standard exception-info popup, after which my host-app simply crashes, without giving me a chance to step-through the `catch` block (and I can't easily/quickly write logging code to see if there's more information there). All I see is:

> FatalExecutionEngineError occurred
> Message: Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\Program Files\IIS Express\iisexpress.exe'.
> Additional information: The runtime has encountered a fatal error. The address of the error was at 0x176b8ed0, on thread 0x62ac. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.

I do understand that the input is likely bad, as I was appending "a" characters, one by one, to a valid "ga" zbase32-encoded text. Perhaps [this ]( https://github.com/wiry-net/Base32/issues/2) is related. This is bad, as I can't even rely on error-handling code to determine bad input.

**Comment by dmitry-ra** [comment]
Shipped in [v1.0.6](https://www.nuget.org/packages/Wiry.Base32/1.0.6)
